---
language: generic
install: true
script:
- mvn clean package
notifications:
  webhooks:
    - https://teams.microsoft.com/l/team/19%3a2JZObWxvr_nZ2jdWHTvuW6Z2L9CfKRJAsTBRs0WCeuk1%40thread.tacv2/conversations?groupId=56381282-b613-434f-86e8-3fa37257d786&tenantId=36da45f1-dd2c-4d1f-af13-5abe46b99921
